.\" Copyright 2026 Tristan Isham. All rights reserved.
.TH ZVM-VERSION 1 "August 2026" "ZVM" "User Commands"
.SH NAME
zvm-version \- print the installed ZVM version
.SH SYNOPSIS
.B zvm version
.SH DESCRIPTION
Print the installed ZVM release version.
The global
.B zvm --version
option additionally prints the target operating system and architecture.
.SH SEE ALSO
.BR zvm (1)
