// Copyright 2026 Tristan Isham. All rights reserved.
// Use of this source code is governed by the MIT
// license that can be found in the LICENSE file.

package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	opts "github.com/urfave/cli/v3"

	"github.com/tristanisham/zvm/cli/meta"
)

// skillReferencePath is the generated command reference consumed by the
// zig-versions skill. SKILL.md itself is hand-written and never generated.
var skillReferencePath = filepath.Join("skills", "zig-versions", "reference", "commands.md")

var updateSkillReference = flag.Bool("update", false, "rewrite the generated skill command reference")

// TestSkillReference keeps the Claude Code skill's command reference in step
// with the CLI it documents. A command or flag added without regenerating the
// reference fails here, which means it fails CI at pull-request time rather
// than surfacing as a skill that teaches agents flags that no longer exist.
//
// Regenerate with:
//
//	go test -run TestSkillReference -update
func TestSkillReference(t *testing.T) {
	want := renderSkillReference()

	if *updateSkillReference {
		if err := os.MkdirAll(filepath.Dir(skillReferencePath), 0o755); err != nil {
			t.Fatalf("creating reference directory: %v", err)
		}
		if err := os.WriteFile(skillReferencePath, []byte(want), 0o644); err != nil {
			t.Fatalf("writing %s: %v", skillReferencePath, err)
		}
		t.Logf("wrote %s", skillReferencePath)
		return
	}

	got, err := os.ReadFile(skillReferencePath)
	if err != nil {
		t.Fatalf("reading %s: %v\nRegenerate with: go test -run TestSkillReference -update", skillReferencePath, err)
	}

	if string(got) != want {
		t.Errorf("%s is out of date with zvm's command surface.\nRegenerate with: go test -run TestSkillReference -update", skillReferencePath)
	}
}

// renderSkillReference builds the full command reference from the live CLI
// definition, so the skill can never drift from the binary.
func renderSkillReference() string {
	var b strings.Builder

	b.WriteString("<!-- Generated by `go test -run TestSkillReference -update`. Do not edit by hand. -->\n\n")
	b.WriteString("# zvm command reference\n\n")
	b.WriteString("Generated from zvm's CLI definition. Every command and flag below is\n")
	b.WriteString("real; anything not listed here does not exist.\n\n")
	fmt.Fprintf(&b, "`%s` — %s\n\n", zvmApp.Name, zvmApp.Usage)

	b.WriteString("## Global flags\n\n")
	if lines := renderFlags(zvmApp.Flags); len(lines) > 0 {
		b.WriteString(strings.Join(lines, "\n") + "\n")
	}
	// urfave/cli adds these during setup, which only happens once the command
	// has been run. Listing them statically keeps this file identical whether
	// or not another test in this package has already run the app.
	b.WriteString("- `--help`, `-h` — show help\n")
	b.WriteString("- `--version`, `-v` — print the version\n\n")

	for _, command := range zvmApp.Commands {
		writeCommand(&b, command, "zvm")
	}

	b.WriteString("## `zvm completion`\n\n")
	b.WriteString("Generate a shell completion script for `bash`, `zsh`, `fish`, or `pwsh`.\n")
	b.WriteString("Generated by urfave/cli rather than declared in main.go.\n")

	return b.String()
}

func writeCommand(b *strings.Builder, command *opts.Command, parent string) {
	// "help" and "completion" are generated by urfave/cli rather than declared
	// in main.go, so they appear only after the app has been set up. Skipping
	// them keeps the output stable across test orderings; "zvm completion" is
	// documented statically below instead.
	if command.Hidden || command.Name == "help" || command.Name == "completion" {
		return
	}

	full := parent + " " + command.Name

	fmt.Fprintf(b, "## `%s`\n\n", full)

	if command.Usage != "" {
		b.WriteString(command.Usage + "\n\n")
	}

	if len(command.Aliases) > 0 {
		quoted := make([]string, 0, len(command.Aliases))
		for _, alias := range command.Aliases {
			quoted = append(quoted, "`"+parent+" "+alias+"`")
		}
		b.WriteString("Aliases: " + strings.Join(quoted, ", ") + "\n\n")
	}

	if usage := strings.TrimSpace(command.ArgsUsage); usage != "" {
		fmt.Fprintf(b, "Arguments: `%s`\n\n", usage)
	}

	if description := strings.TrimSpace(command.Description); description != "" {
		b.WriteString(description + "\n\n")
	}

	if lines := renderFlags(command.Flags); len(lines) > 0 {
		b.WriteString(strings.Join(lines, "\n") + "\n\n")
	}

	for _, sub := range command.Commands {
		writeCommand(b, sub, full)
	}
}

func renderFlags(flags []opts.Flag) []string {
	var lines []string

	for _, f := range flags {
		names := f.Names()
		if len(names) == 0 {
			continue
		}

		rendered := make([]string, 0, len(names))
		for _, name := range names {
			// Generated by urfave/cli during setup; documented statically.
			if name == "help" || name == "h" || name == "version" || name == "v" {
				continue
			}
			prefix := "--"
			if len(name) == 1 {
				prefix = "-"
			}
			rendered = append(rendered, "`"+prefix+name+"`")
		}
		if len(rendered) == 0 {
			continue
		}

		line := strings.Join(rendered, ", ")
		if doc, ok := f.(opts.DocGenerationFlag); ok {
			if usage := strings.TrimSpace(doc.GetUsage()); usage != "" {
				line += " — " + usage
			}
		}

		lines = append(lines, "- "+line)
	}

	return lines
}

// pluginManifests are the plugin manifests whose "version" must track
// cli/meta/version.go.
var pluginManifests = []string{
	filepath.Join(".claude-plugin", "plugin.json"),
	filepath.Join(".claude-plugin", "marketplace.json"),
}

// pluginVersionRe matches the "version" field in the plugin manifests. A
// targeted rewrite preserves hand-authored formatting and key order, which
// round-tripping through encoding/json would not.
var pluginVersionRe = regexp.MustCompile(`("version"\s*:\s*)"[^"]*"`)

// TestPluginVersionMatchesMeta keeps the published plugin version in step with
// the zvm release it documents.
//
// Sync with:
//
//	go test -run TestPluginVersionMatchesMeta -update
func TestPluginVersionMatchesMeta(t *testing.T) {
	want := strings.TrimPrefix(meta.VERSION, "v")

	for _, manifest := range pluginManifests {
		contents, err := os.ReadFile(manifest)
		if err != nil {
			t.Fatalf("reading %s: %v", manifest, err)
		}

		if *updateSkillReference {
			updated := pluginVersionRe.ReplaceAll(contents, []byte(`${1}"`+want+`"`))
			if !bytes.Equal(updated, contents) {
				if err := os.WriteFile(manifest, updated, 0o644); err != nil {
					t.Fatalf("writing %s: %v", manifest, err)
				}
				t.Logf("synced %s to %s", manifest, want)
			}
			continue
		}

		var manifestVersions []string
		for _, line := range pluginVersionRe.FindAllString(string(contents), -1) {
			manifestVersions = append(manifestVersions, strings.Trim(strings.SplitN(line, ":", 2)[1], " \""))
		}

		if len(manifestVersions) == 0 {
			t.Errorf("%s declares no version field", manifest)
			continue
		}

		for _, got := range manifestVersions {
			if got != want {
				t.Errorf("%s declares version %q, want %q (from cli/meta.VERSION).\nSync with: go test -run TestPluginVersionMatchesMeta -update", manifest, got, want)
			}
		}
	}
}
